### ISSUE TITLE
undefined is not valid JSON

### ISSUE THREAD

**Issue by iplayfast** [technovangelist/airenamer#3]
aipicturerenamer 
error: Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at getkeywords (file:///home/runner/work/airenamer/airenamer/main.ts:20:25)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/runner/work/airenamer/airenamer/main.ts:33:24

**Comment by technovangelist** [comment]
should be fixed now. thanks
