### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by iplayfast** [technovangelist/airenamer#6]
I called it picture_labler as that seemed more descriptive. When running I get this.

```picture_labler .
Error: 404: Not Found
error: Uncaught (in promise) Error: Is a directory (os error 21): copy '/home/chris/Pictures/Screenshot from 2023-02-03 10-10-20.png' -> '/home/chris/Pictures/'
    at Object.copyFileSync (ext:deno_fs/30_fs.js:72:7)
    at file:///home/runner/work/airenamer/airenamer/main.ts:47:12
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by technovangelist** [comment]
if this is still happening, let me know. will close .
