### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by jekakiev** [technovangelist/airenamer#7]
error: Uncaught (in promise) TypeError: error sending request for url (http://localhost:11434/api/generate): error trying to connect: tcp connect error: Connection refused (os error 61)
    at async mainFetch (ext:deno_fetch/26_fetch.js:277:12)
    at async fetch (ext:deno_fetch/26_fetch.js:504:7)
    at async getkeywords (file:///home/runner/work/airenamer/airenamer/main.ts:12:20)
    at async file:///home/runner/work/airenamer/airenamer/main.ts:45:24

**Comment by technovangelist** [comment]
the server isn't running. Is ollama installed? or is the service running?

**Comment by jekakiev** [comment]
Now I run it, but here is new error:
error: Uncaught (in promise) Error: Is a directory (os error 21): copy '/Users/yevhenii/Downloads/253/20240122135847873342000000-o.jpg' -> '/Users/yevhenii/Downloads/253/'
    at Object.copyFileSync (ext:deno_fs/30_fs.js:72:7)
    at file:///home/runner/work/airenamer/airenamer/main.ts:47:12
    at eventLoopTick (ext:core/01_core.js:183:11)
***@***.*** 253 %

**Comment by jekakiev** [comment]
yevhenii@MBP-Yevhenii 253 % airenamer
Error: 404: Not Found
error: Uncaught (in promise) Error: Is a directory (os error 21): copy '/Users/yevhenii/Downloads/253/20240122135847873342000000-o.jpg' -> '/Users/yevhenii/Downloads/253/'
    at Object.copyFileSync (ext:deno_fs/30_fs.js:72:7)
    at file:///home/runner/work/airenamer/airenamer/main.ts:47:12
    at eventLoopTick (ext:core/01_core.js:183:11)
yevhenii@MBP-Yevhenii 253 %
